/// Tests for signature algorithms

import "package:flutter_test/flutter_test.dart";

import "../lib/src/api/sign.dart";


void main(){
  String secretId = 'fake-secret-id';
  String secretKey = 'fake-secret-key';
  String method = 'GET';
  String host = 'service.cos.myqcloud.com';
  String path = '/';
  Map<String, dynamic> queryParams = {};
  Map<String, String> headers = {'Content-Type': 'application/xml', 'Host': host};
  int beginTime = 1648134580;
  int expire = 3600;

  String keyTime = '1648134580;1648138180';
  String httpParameters = '';
  String headerList = 'content-type;host';
  String httpHeaders = 'content-type=application%2Fxml&host=service.cos.myqcloud.com';
  String httpString = 'get\n/\n\ncontent-type=application%2Fxml&host=service.cos.myqcloud.com\n';
  String stringToSign = 'sha1\n1648134580;1648138180\n323944bc3a45e5f9c7273632f53013f844fe987c\n';

  // generated by official validation tools
  // https://cos5.cloud.tencent.com/static/cos-sign/
  String authString = 'q-sign-algorithm=sha1&q-ak=fake-secret-id&q-sign-time=1648134580;1648138180&q-key-time=1648134580;1648138180&q-header-list=content-type;host&q-url-param-list=&q-signature=a95459d05fc94d74d9917fe08fd4aa231f590ed7';

  test('joinHttpParams', (){
    Map<String, dynamic> rawQueryParams = {
      'prefix': 'example-folder/',
      'delimiter': '/',
      'max-keys': 10,
      'test': null
    };
    String encodedQueryParams = joinHttpParams(rawQueryParams);
    expect(encodedQueryParams, 'delimiter=%2F&max-keys=10&prefix=example-folder%2F&test=');
  });
  test('主函数',(){
    String result = calculateAuthString(
        method, path, queryParams, headers, secretId, secretKey,
        beginTime: beginTime, expire: expire
    );
    expect(result, authString);
  });
}
